version: 2

jobs:
  build:
    docker:
      - image: qrntz/tklc:circleci
    working_directory: ~/product
    environment:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build & push product image
          command: "/usr/share/tklc/circleci-build.sh"
      - run:
          name: Test deployment
          command: "if [[ -x test.sh ]]; then ./test.sh; done"

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: "awsecr"
