version: 2

jobs:
  build:
    docker:
      - image: qrntz/tklc:circleci
    working_directory: ~/product
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: tar czf - . | docker run --rm -i qrntz/keyhole-builder:master > keyhole.tar.gz
      - run: ls -lah
