version: 2

jobs:
  build:
    docker:
      - image: qrntz/tklc:circleci
    working_directory: ~/product
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker pull qrntz/keyhole-builder:master
          tar czf - . | docker run --name keyhole -i qrntz/keyhole-builder:master
          docker cp keyhole:keyhole .
          ls -lah
